#!/usr/bin/env bash
# Runs on the HOST via initializeCommand before the container is created or started.
# Idempotent — safe to run on every devcontainer open.
#
# Responsibilities:
#   1. Generate .devcontainer/.env with the host-expanded $HOME path (once).
#   2. Compute the workspace bind-mount paths (required because compose,
#      unlike an image-based devcontainer, does not auto-mount the source).
#   3. Symlink .env into each variant subdirectory so Docker Compose picks it up.
#   4. Pre-create the Claude persist directory on the host so the bind mount succeeds.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_ENV="${SCRIPT_DIR}/.env"

# Workspace folder. The devcontainer initializeCommand passes the real
# ${localWorkspaceFolder} as $1, which may be a subdirectory of this repo
# (e.g. a nested project that reuses this shared .devcontainer). When run
# manually with no argument, fall back to the parent of .devcontainer.
WORKSPACE_ROOT="$(cd "${1:-${SCRIPT_DIR}/..}" && pwd)"
WORKSPACE_BASENAME="$(basename "$WORKSPACE_ROOT")"

# Append KEY=VALUE to .env only if KEY is not already present.
# Lets an existing .env pick up variables added in later versions of this file.
ensure_env() {
  local key="$1" value="$2"
  grep -q "^${key}=" "$SHARED_ENV" 2>/dev/null && return 0
  printf '%s=%s\n' "$key" "$value" >> "$SHARED_ENV"
  echo "[init] Added ${key} to .env"
}

# Set KEY=VALUE in .env, replacing any existing line. Used for values that
# change between launches (the workspace differs per project that reuses
# this shared config), so append-if-missing is not enough.
upsert_env() {
  local key="$1" value="$2"
  [ -f "$SHARED_ENV" ] && sed -i.bak "/^${key}=/d" "$SHARED_ENV" && rm -f "${SHARED_ENV}.bak"
  printf '%s=%s\n' "$key" "$value" >> "$SHARED_ENV"
}

if [ ! -f "$SHARED_ENV" ]; then
  cat > "$SHARED_ENV" <<EOF
# Generated by .devcontainer/init.sh — do not commit (see .gitignore).
# Edit to change paths or defaults; re-open the devcontainer to apply.

# Absolute path to your SSH keys on the host.
# Bind-mounted read-only into the container for private git submodule access.
# System-wide known_hosts are baked into the image so this can stay read-only.
SSH_DIR=${HOME}/.ssh

# Absolute path to your AWS credentials and config on the host.
# Bind-mounted read-write so aws configure / aws sso login work inside the container.
# Never copied into the image.
AWS_CONFIG_DIR=${HOME}/.aws

# Absolute path on the host where Claude Code config and data persist across rebuilds.
# All devcontainer variants (base, csharp, …) share this single directory.
CLAUDE_PERSIST_HOST_DIR=${HOME}/.devcontainer-claude

# Docker socket path.
# Standard (Docker Desktop / rootful): /var/run/docker.sock
# Rootless Docker on Linux:            /run/user/$(id -u)/docker.sock
DOCKER_SOCK=/var/run/docker.sock

# GID of the docker group on the host.
# Find it with: stat -c '%g' /var/run/docker.sock   (Linux)
#               stat -f '%g' /var/run/docker.sock   (macOS)
# Leave as "docker" if the name resolves correctly inside the container.
DOCKER_GID=docker

# Tag for the base image built by build.sh
BASE_IMAGE=aws-lambda-base:latest

# .NET SDK major version for the C# devcontainer
DOTNET_VERSION=9.0

# Python version for the Python devcontainer (must match an active Lambda runtime)
# Supported: 3.13 (default), 3.12, 3.11
PYTHON_VERSION=3.13

# ── Shared dependency caches ──────────────────────────────────────────────────
# Host directories (default under \$HOME) bind-mounted into the language variants
# at each tool's default cache/store location. Package downloads are therefore
# shared across every project and container, and survive rebuilds.
NPM_CACHE_HOST_DIR=${HOME}/.devcontainer-cache/npm        # → /home/vscode/.npm
PNPM_STORE_HOST_DIR=${HOME}/.devcontainer-cache/pnpm      # → ~/.local/share/pnpm/store
UV_CACHE_HOST_DIR=${HOME}/.devcontainer-cache/uv          # → /home/vscode/.cache/uv
NUGET_HOST_DIR=${HOME}/.devcontainer-cache/nuget          # → /home/vscode/.nuget/packages
EOF
  echo "[init] Created .devcontainer/.env"
fi

# Workspace bind-mount paths. Refreshed on every run (upsert) because the
# workspace differs per project when this shared config is reused.
# LOCAL_WORKSPACE_FOLDER : host path mounted into the container
# WORKSPACE_FOLDER       : container path — must match "workspaceFolder" in
#                          devcontainer.json (/workspaces/<basename>).
upsert_env LOCAL_WORKSPACE_FOLDER "$WORKSPACE_ROOT"
upsert_env WORKSPACE_FOLDER       "/workspaces/${WORKSPACE_BASENAME}"
echo "[init] workspace → ${WORKSPACE_ROOT} (mounts at /workspaces/${WORKSPACE_BASENAME})"

# Shared dependency cache paths — appended to a pre-existing .env that predates them.
ensure_env NPM_CACHE_HOST_DIR  "${HOME}/.devcontainer-cache/npm"
ensure_env PNPM_STORE_HOST_DIR "${HOME}/.devcontainer-cache/pnpm"
ensure_env UV_CACHE_HOST_DIR   "${HOME}/.devcontainer-cache/uv"
ensure_env NUGET_HOST_DIR      "${HOME}/.devcontainer-cache/nuget"

# The top-level config reads .env directly. Any variant subfolders need a
# symlink back to the shared .env (Docker Compose looks for .env next to the
# compose file). The "-d" guard makes this a no-op when there are no subfolders
# — e.g. a self-contained .devcontainer scaffolded into a single project.
for subdir in csharp python typescript; do
  dir="${SCRIPT_DIR}/${subdir}"
  [ -d "$dir" ] || continue
  link="${dir}/.env"
  [ -e "$link" ] || ln -sf "../.env" "$link"
done

# Pre-create the host directories the container bind-mounts, so the mounts
# succeed (and aren't created root-owned by the Docker daemon on first use).
# bash can source the .env file (# comments are valid shell comments).
# shellcheck disable=SC1090
set -a; source "$SHARED_ENV"; set +a
mkdir -p \
  "${CLAUDE_PERSIST_HOST_DIR}" \
  "${NPM_CACHE_HOST_DIR}" \
  "${PNPM_STORE_HOST_DIR}" \
  "${UV_CACHE_HOST_DIR}" \
  "${NUGET_HOST_DIR}"
